/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Random_postRouteImport } from './routes/random_post'
import { Route as MeRouteImport } from './routes/me'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as AtusernameRouteImport } from './routes/@$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UMeRouteImport } from './routes/u.me'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as CommentIdRouteImport } from './routes/comment.$id'
import { Route as AtusernamePostsRouteImport } from './routes/@$username_.posts'
import { Route as UUsernamePostsRouteImport } from './routes/u.$username_.posts'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Random_postRoute = Random_postRouteImport.update({
  id: '/random_post',
  path: '/random_post',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AtusernameRoute = AtusernameRouteImport.update({
  id: '/@$username',
  path: '/@$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UMeRoute = UMeRouteImport.update({
  id: '/u/me',
  path: '/u/me',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentIdRoute = CommentIdRouteImport.update({
  id: '/comment/$id',
  path: '/comment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtusernamePostsRoute = AtusernamePostsRouteImport.update({
  id: '/@$username_/posts',
  path: '/@$username/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernamePostsRoute = UUsernamePostsRouteImport.update({
  id: '/u/$username_/posts',
  path: '/u/$username/posts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@$username': typeof AtusernameRoute
  '/comments': typeof CommentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/me': typeof MeRoute
  '/random_post': typeof Random_postRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/@$username/posts': typeof AtusernamePostsRoute
  '/comment/$id': typeof CommentIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/me': typeof UMeRoute
  '/u/$username/posts': typeof UUsernamePostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@$username': typeof AtusernameRoute
  '/comments': typeof CommentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/me': typeof MeRoute
  '/random_post': typeof Random_postRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/@$username/posts': typeof AtusernamePostsRoute
  '/comment/$id': typeof CommentIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/me': typeof UMeRoute
  '/u/$username/posts': typeof UUsernamePostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@$username': typeof AtusernameRoute
  '/comments': typeof CommentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/me': typeof MeRoute
  '/random_post': typeof Random_postRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/@$username_/posts': typeof AtusernamePostsRoute
  '/comment/$id': typeof CommentIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/me': typeof UMeRoute
  '/u/$username_/posts': typeof UUsernamePostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@$username'
    | '/comments'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/me'
    | '/random_post'
    | '/reset-password'
    | '/signup'
    | '/submit'
    | '/@$username/posts'
    | '/comment/$id'
    | '/post/$id'
    | '/u/$username'
    | '/u/me'
    | '/u/$username/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@$username'
    | '/comments'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/me'
    | '/random_post'
    | '/reset-password'
    | '/signup'
    | '/submit'
    | '/@$username/posts'
    | '/comment/$id'
    | '/post/$id'
    | '/u/$username'
    | '/u/me'
    | '/u/$username/posts'
  id:
    | '__root__'
    | '/'
    | '/@$username'
    | '/comments'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/me'
    | '/random_post'
    | '/reset-password'
    | '/signup'
    | '/submit'
    | '/@$username_/posts'
    | '/comment/$id'
    | '/post/$id'
    | '/u/$username'
    | '/u/me'
    | '/u/$username_/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtusernameRoute: typeof AtusernameRoute
  CommentsRoute: typeof CommentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MeRoute: typeof MeRoute
  Random_postRoute: typeof Random_postRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SubmitRoute: typeof SubmitRoute
  AtusernamePostsRoute: typeof AtusernamePostsRoute
  CommentIdRoute: typeof CommentIdRoute
  PostIdRoute: typeof PostIdRoute
  UUsernameRoute: typeof UUsernameRoute
  UMeRoute: typeof UMeRoute
  UUsernamePostsRoute: typeof UUsernamePostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random_post': {
      id: '/random_post'
      path: '/random_post'
      fullPath: '/random_post'
      preLoaderRoute: typeof Random_postRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$username': {
      id: '/@$username'
      path: '/@$username'
      fullPath: '/@$username'
      preLoaderRoute: typeof AtusernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/me': {
      id: '/u/me'
      path: '/u/me'
      fullPath: '/u/me'
      preLoaderRoute: typeof UMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment/$id': {
      id: '/comment/$id'
      path: '/comment/$id'
      fullPath: '/comment/$id'
      preLoaderRoute: typeof CommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$username_/posts': {
      id: '/@$username_/posts'
      path: '/@$username/posts'
      fullPath: '/@$username/posts'
      preLoaderRoute: typeof AtusernamePostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/posts': {
      id: '/u/$username_/posts'
      path: '/u/$username/posts'
      fullPath: '/u/$username/posts'
      preLoaderRoute: typeof UUsernamePostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtusernameRoute: AtusernameRoute,
  CommentsRoute: CommentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MeRoute: MeRoute,
  Random_postRoute: Random_postRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SubmitRoute: SubmitRoute,
  AtusernamePostsRoute: AtusernamePostsRoute,
  CommentIdRoute: CommentIdRoute,
  PostIdRoute: PostIdRoute,
  UUsernameRoute: UUsernameRoute,
  UMeRoute: UMeRoute,
  UUsernamePostsRoute: UUsernamePostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
