/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as Random_userRouteImport } from './routes/random_user'
import { Route as Random_postRouteImport } from './routes/random_post'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModlogRouteImport } from './routes/modlog'
import { Route as ModLogRouteImport } from './routes/mod-log'
import { Route as MeRouteImport } from './routes/me'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogRouteImport } from './routes/log'
import { Route as FormattingRouteImport } from './routes/formatting'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtmeRouteImport } from './routes/@me'
import { Route as AtusernameRouteImport } from './routes/@$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UMeRouteImport } from './routes/u.me'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as CommentIdRouteImport } from './routes/comment.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportedPostsRouteImport } from './routes/admin.reported-posts'
import { Route as AdminReportedCommentsRouteImport } from './routes/admin.reported-comments'
import { Route as AdminModLogRouteImport } from './routes/admin.mod-log'
import { Route as AdminFilteredRouteImport } from './routes/admin.filtered'
import { Route as AdminBulkModerationRouteImport } from './routes/admin.bulk-moderation'
import { Route as AdminBannedDomainsRouteImport } from './routes/admin.banned-domains'
import { Route as AdminBadgesRouteImport } from './routes/admin.badges'
import { Route as AtusernamePostsRouteImport } from './routes/@$username_.posts'
import { Route as UUsernamePostsRouteImport } from './routes/u.$username_.posts'
import { Route as UUsernameFollowingRouteImport } from './routes/u.$username_.following'
import { Route as UUsernameFollowersRouteImport } from './routes/u.$username_.followers'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users_.$id'
import { Route as AtusernameSavedPostsRouteImport } from './routes/@$username_.saved.posts'
import { Route as AtusernameSavedCommentsRouteImport } from './routes/@$username_.saved.comments'
import { Route as UUsernameSavedPostsRouteImport } from './routes/u.$username_.saved.posts'
import { Route as UUsernameSavedCommentsRouteImport } from './routes/u.$username_.saved.comments'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const Random_userRoute = Random_userRouteImport.update({
  id: '/random_user',
  path: '/random_user',
  getParentRoute: () => rootRouteImport,
} as any)
const Random_postRoute = Random_postRouteImport.update({
  id: '/random_post',
  path: '/random_post',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModlogRoute = ModlogRouteImport.update({
  id: '/modlog',
  path: '/modlog',
  getParentRoute: () => rootRouteImport,
} as any)
const ModLogRoute = ModLogRouteImport.update({
  id: '/mod-log',
  path: '/mod-log',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const FormattingRoute = FormattingRouteImport.update({
  id: '/formatting',
  path: '/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmeRoute = AtmeRouteImport.update({
  id: '/@me',
  path: '/@me',
  getParentRoute: () => rootRouteImport,
} as any)
const AtusernameRoute = AtusernameRouteImport.update({
  id: '/@$username',
  path: '/@$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UMeRoute = UMeRouteImport.update({
  id: '/u/me',
  path: '/u/me',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentIdRoute = CommentIdRouteImport.update({
  id: '/comment/$id',
  path: '/comment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportedPostsRoute = AdminReportedPostsRouteImport.update({
  id: '/reported-posts',
  path: '/reported-posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportedCommentsRoute = AdminReportedCommentsRouteImport.update({
  id: '/reported-comments',
  path: '/reported-comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModLogRoute = AdminModLogRouteImport.update({
  id: '/mod-log',
  path: '/mod-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilteredRoute = AdminFilteredRouteImport.update({
  id: '/filtered',
  path: '/filtered',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkModerationRoute = AdminBulkModerationRouteImport.update({
  id: '/bulk-moderation',
  path: '/bulk-moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannedDomainsRoute = AdminBannedDomainsRouteImport.update({
  id: '/banned-domains',
  path: '/banned-domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const AtusernamePostsRoute = AtusernamePostsRouteImport.update({
  id: '/@$username_/posts',
  path: '/@$username/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernamePostsRoute = UUsernamePostsRouteImport.update({
  id: '/u/$username_/posts',
  path: '/u/$username/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFollowingRoute = UUsernameFollowingRouteImport.update({
  id: '/u/$username_/following',
  path: '/u/$username/following',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFollowersRoute = UUsernameFollowersRouteImport.update({
  id: '/u/$username_/followers',
  path: '/u/$username/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AtusernameSavedPostsRoute = AtusernameSavedPostsRouteImport.update({
  id: '/@$username_/saved/posts',
  path: '/@$username/saved/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AtusernameSavedCommentsRoute = AtusernameSavedCommentsRouteImport.update({
  id: '/@$username_/saved/comments',
  path: '/@$username/saved/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameSavedPostsRoute = UUsernameSavedPostsRouteImport.update({
  id: '/u/$username_/saved/posts',
  path: '/u/$username/saved/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameSavedCommentsRoute = UUsernameSavedCommentsRouteImport.update({
  id: '/u/$username_/saved/comments',
  path: '/u/$username/saved/comments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@$username': typeof AtusernameRoute
  '/@me': typeof AtmeRoute
  '/admin': typeof AdminRouteWithChildren
  '/admins': typeof AdminsRoute
  '/banned': typeof BannedRoute
  '/catalog': typeof CatalogRoute
  '/comments': typeof CommentsRoute
  '/forgot': typeof ForgotRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formatting': typeof FormattingRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/me': typeof MeRoute
  '/mod-log': typeof ModLogRoute
  '/modlog': typeof ModlogRoute
  '/notifications': typeof NotificationsRoute
  '/random_post': typeof Random_postRoute
  '/random_user': typeof Random_userRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/submit': typeof SubmitRoute
  '/verify-email': typeof VerifyEmailRoute
  '/@$username/posts': typeof AtusernamePostsRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/banned-domains': typeof AdminBannedDomainsRoute
  '/admin/bulk-moderation': typeof AdminBulkModerationRoute
  '/admin/filtered': typeof AdminFilteredRoute
  '/admin/mod-log': typeof AdminModLogRoute
  '/admin/reported-comments': typeof AdminReportedCommentsRoute
  '/admin/reported-posts': typeof AdminReportedPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/comment/$id': typeof CommentIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/me': typeof UMeRoute
  '/admin/': typeof AdminIndexRoute
  '/@$username/saved/comments': typeof AtusernameSavedCommentsRoute
  '/@$username/saved/posts': typeof AtusernameSavedPostsRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/u/$username/posts': typeof UUsernamePostsRoute
  '/u/$username/saved/comments': typeof UUsernameSavedCommentsRoute
  '/u/$username/saved/posts': typeof UUsernameSavedPostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@$username': typeof AtusernameRoute
  '/@me': typeof AtmeRoute
  '/admins': typeof AdminsRoute
  '/banned': typeof BannedRoute
  '/catalog': typeof CatalogRoute
  '/comments': typeof CommentsRoute
  '/forgot': typeof ForgotRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formatting': typeof FormattingRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/me': typeof MeRoute
  '/mod-log': typeof ModLogRoute
  '/modlog': typeof ModlogRoute
  '/notifications': typeof NotificationsRoute
  '/random_post': typeof Random_postRoute
  '/random_user': typeof Random_userRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/submit': typeof SubmitRoute
  '/verify-email': typeof VerifyEmailRoute
  '/@$username/posts': typeof AtusernamePostsRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/banned-domains': typeof AdminBannedDomainsRoute
  '/admin/bulk-moderation': typeof AdminBulkModerationRoute
  '/admin/filtered': typeof AdminFilteredRoute
  '/admin/mod-log': typeof AdminModLogRoute
  '/admin/reported-comments': typeof AdminReportedCommentsRoute
  '/admin/reported-posts': typeof AdminReportedPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/comment/$id': typeof CommentIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/me': typeof UMeRoute
  '/admin': typeof AdminIndexRoute
  '/@$username/saved/comments': typeof AtusernameSavedCommentsRoute
  '/@$username/saved/posts': typeof AtusernameSavedPostsRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/u/$username/posts': typeof UUsernamePostsRoute
  '/u/$username/saved/comments': typeof UUsernameSavedCommentsRoute
  '/u/$username/saved/posts': typeof UUsernameSavedPostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@$username': typeof AtusernameRoute
  '/@me': typeof AtmeRoute
  '/admin': typeof AdminRouteWithChildren
  '/admins': typeof AdminsRoute
  '/banned': typeof BannedRoute
  '/catalog': typeof CatalogRoute
  '/comments': typeof CommentsRoute
  '/forgot': typeof ForgotRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formatting': typeof FormattingRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/me': typeof MeRoute
  '/mod-log': typeof ModLogRoute
  '/modlog': typeof ModlogRoute
  '/notifications': typeof NotificationsRoute
  '/random_post': typeof Random_postRoute
  '/random_user': typeof Random_userRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/submit': typeof SubmitRoute
  '/verify-email': typeof VerifyEmailRoute
  '/@$username_/posts': typeof AtusernamePostsRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/banned-domains': typeof AdminBannedDomainsRoute
  '/admin/bulk-moderation': typeof AdminBulkModerationRoute
  '/admin/filtered': typeof AdminFilteredRoute
  '/admin/mod-log': typeof AdminModLogRoute
  '/admin/reported-comments': typeof AdminReportedCommentsRoute
  '/admin/reported-posts': typeof AdminReportedPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/comment/$id': typeof CommentIdRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/u/me': typeof UMeRoute
  '/admin/': typeof AdminIndexRoute
  '/@$username_/saved/comments': typeof AtusernameSavedCommentsRoute
  '/@$username_/saved/posts': typeof AtusernameSavedPostsRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/u/$username_/followers': typeof UUsernameFollowersRoute
  '/u/$username_/following': typeof UUsernameFollowingRoute
  '/u/$username_/posts': typeof UUsernamePostsRoute
  '/u/$username_/saved/comments': typeof UUsernameSavedCommentsRoute
  '/u/$username_/saved/posts': typeof UUsernameSavedPostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@$username'
    | '/@me'
    | '/admin'
    | '/admins'
    | '/banned'
    | '/catalog'
    | '/comments'
    | '/forgot'
    | '/forgot-password'
    | '/formatting'
    | '/log'
    | '/login'
    | '/logout'
    | '/me'
    | '/mod-log'
    | '/modlog'
    | '/notifications'
    | '/random_post'
    | '/random_user'
    | '/reset'
    | '/reset-password'
    | '/rules'
    | '/search'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/submit'
    | '/verify-email'
    | '/@$username/posts'
    | '/admin/badges'
    | '/admin/banned-domains'
    | '/admin/bulk-moderation'
    | '/admin/filtered'
    | '/admin/mod-log'
    | '/admin/reported-comments'
    | '/admin/reported-posts'
    | '/admin/settings'
    | '/admin/users'
    | '/comment/$id'
    | '/post/$id'
    | '/u/$username'
    | '/u/me'
    | '/admin/'
    | '/@$username/saved/comments'
    | '/@$username/saved/posts'
    | '/admin/users/$id'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username/posts'
    | '/u/$username/saved/comments'
    | '/u/$username/saved/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@$username'
    | '/@me'
    | '/admins'
    | '/banned'
    | '/catalog'
    | '/comments'
    | '/forgot'
    | '/forgot-password'
    | '/formatting'
    | '/log'
    | '/login'
    | '/logout'
    | '/me'
    | '/mod-log'
    | '/modlog'
    | '/notifications'
    | '/random_post'
    | '/random_user'
    | '/reset'
    | '/reset-password'
    | '/rules'
    | '/search'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/submit'
    | '/verify-email'
    | '/@$username/posts'
    | '/admin/badges'
    | '/admin/banned-domains'
    | '/admin/bulk-moderation'
    | '/admin/filtered'
    | '/admin/mod-log'
    | '/admin/reported-comments'
    | '/admin/reported-posts'
    | '/admin/settings'
    | '/admin/users'
    | '/comment/$id'
    | '/post/$id'
    | '/u/$username'
    | '/u/me'
    | '/admin'
    | '/@$username/saved/comments'
    | '/@$username/saved/posts'
    | '/admin/users/$id'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username/posts'
    | '/u/$username/saved/comments'
    | '/u/$username/saved/posts'
  id:
    | '__root__'
    | '/'
    | '/@$username'
    | '/@me'
    | '/admin'
    | '/admins'
    | '/banned'
    | '/catalog'
    | '/comments'
    | '/forgot'
    | '/forgot-password'
    | '/formatting'
    | '/log'
    | '/login'
    | '/logout'
    | '/me'
    | '/mod-log'
    | '/modlog'
    | '/notifications'
    | '/random_post'
    | '/random_user'
    | '/reset'
    | '/reset-password'
    | '/rules'
    | '/search'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/submit'
    | '/verify-email'
    | '/@$username_/posts'
    | '/admin/badges'
    | '/admin/banned-domains'
    | '/admin/bulk-moderation'
    | '/admin/filtered'
    | '/admin/mod-log'
    | '/admin/reported-comments'
    | '/admin/reported-posts'
    | '/admin/settings'
    | '/admin/users'
    | '/comment/$id'
    | '/post/$id'
    | '/u/$username'
    | '/u/me'
    | '/admin/'
    | '/@$username_/saved/comments'
    | '/@$username_/saved/posts'
    | '/admin/users_/$id'
    | '/u/$username_/followers'
    | '/u/$username_/following'
    | '/u/$username_/posts'
    | '/u/$username_/saved/comments'
    | '/u/$username_/saved/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtusernameRoute: typeof AtusernameRoute
  AtmeRoute: typeof AtmeRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminsRoute: typeof AdminsRoute
  BannedRoute: typeof BannedRoute
  CatalogRoute: typeof CatalogRoute
  CommentsRoute: typeof CommentsRoute
  ForgotRoute: typeof ForgotRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormattingRoute: typeof FormattingRoute
  LogRoute: typeof LogRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MeRoute: typeof MeRoute
  ModLogRoute: typeof ModLogRoute
  ModlogRoute: typeof ModlogRoute
  NotificationsRoute: typeof NotificationsRoute
  Random_postRoute: typeof Random_postRoute
  Random_userRoute: typeof Random_userRoute
  ResetRoute: typeof ResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  SubmitRoute: typeof SubmitRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AtusernamePostsRoute: typeof AtusernamePostsRoute
  CommentIdRoute: typeof CommentIdRoute
  PostIdRoute: typeof PostIdRoute
  UUsernameRoute: typeof UUsernameRoute
  UMeRoute: typeof UMeRoute
  AtusernameSavedCommentsRoute: typeof AtusernameSavedCommentsRoute
  AtusernameSavedPostsRoute: typeof AtusernameSavedPostsRoute
  UUsernameFollowersRoute: typeof UUsernameFollowersRoute
  UUsernameFollowingRoute: typeof UUsernameFollowingRoute
  UUsernamePostsRoute: typeof UUsernamePostsRoute
  UUsernameSavedCommentsRoute: typeof UUsernameSavedCommentsRoute
  UUsernameSavedPostsRoute: typeof UUsernameSavedPostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random_user': {
      id: '/random_user'
      path: '/random_user'
      fullPath: '/random_user'
      preLoaderRoute: typeof Random_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random_post': {
      id: '/random_post'
      path: '/random_post'
      fullPath: '/random_post'
      preLoaderRoute: typeof Random_postRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modlog': {
      id: '/modlog'
      path: '/modlog'
      fullPath: '/modlog'
      preLoaderRoute: typeof ModlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-log': {
      id: '/mod-log'
      path: '/mod-log'
      fullPath: '/mod-log'
      preLoaderRoute: typeof ModLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatting': {
      id: '/formatting'
      path: '/formatting'
      fullPath: '/formatting'
      preLoaderRoute: typeof FormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@me': {
      id: '/@me'
      path: '/@me'
      fullPath: '/@me'
      preLoaderRoute: typeof AtmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$username': {
      id: '/@$username'
      path: '/@$username'
      fullPath: '/@$username'
      preLoaderRoute: typeof AtusernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/me': {
      id: '/u/me'
      path: '/u/me'
      fullPath: '/u/me'
      preLoaderRoute: typeof UMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment/$id': {
      id: '/comment/$id'
      path: '/comment/$id'
      fullPath: '/comment/$id'
      preLoaderRoute: typeof CommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reported-posts': {
      id: '/admin/reported-posts'
      path: '/reported-posts'
      fullPath: '/admin/reported-posts'
      preLoaderRoute: typeof AdminReportedPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reported-comments': {
      id: '/admin/reported-comments'
      path: '/reported-comments'
      fullPath: '/admin/reported-comments'
      preLoaderRoute: typeof AdminReportedCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mod-log': {
      id: '/admin/mod-log'
      path: '/mod-log'
      fullPath: '/admin/mod-log'
      preLoaderRoute: typeof AdminModLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/filtered': {
      id: '/admin/filtered'
      path: '/filtered'
      fullPath: '/admin/filtered'
      preLoaderRoute: typeof AdminFilteredRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-moderation': {
      id: '/admin/bulk-moderation'
      path: '/bulk-moderation'
      fullPath: '/admin/bulk-moderation'
      preLoaderRoute: typeof AdminBulkModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banned-domains': {
      id: '/admin/banned-domains'
      path: '/banned-domains'
      fullPath: '/admin/banned-domains'
      preLoaderRoute: typeof AdminBannedDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/@$username_/posts': {
      id: '/@$username_/posts'
      path: '/@$username/posts'
      fullPath: '/@$username/posts'
      preLoaderRoute: typeof AtusernamePostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/posts': {
      id: '/u/$username_/posts'
      path: '/u/$username/posts'
      fullPath: '/u/$username/posts'
      preLoaderRoute: typeof UUsernamePostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/following': {
      id: '/u/$username_/following'
      path: '/u/$username/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof UUsernameFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/followers': {
      id: '/u/$username_/followers'
      path: '/u/$username/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof UUsernameFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/@$username_/saved/posts': {
      id: '/@$username_/saved/posts'
      path: '/@$username/saved/posts'
      fullPath: '/@$username/saved/posts'
      preLoaderRoute: typeof AtusernameSavedPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$username_/saved/comments': {
      id: '/@$username_/saved/comments'
      path: '/@$username/saved/comments'
      fullPath: '/@$username/saved/comments'
      preLoaderRoute: typeof AtusernameSavedCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/saved/posts': {
      id: '/u/$username_/saved/posts'
      path: '/u/$username/saved/posts'
      fullPath: '/u/$username/saved/posts'
      preLoaderRoute: typeof UUsernameSavedPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/saved/comments': {
      id: '/u/$username_/saved/comments'
      path: '/u/$username/saved/comments'
      fullPath: '/u/$username/saved/comments'
      preLoaderRoute: typeof UUsernameSavedCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminBannedDomainsRoute: typeof AdminBannedDomainsRoute
  AdminBulkModerationRoute: typeof AdminBulkModerationRoute
  AdminFilteredRoute: typeof AdminFilteredRoute
  AdminModLogRoute: typeof AdminModLogRoute
  AdminReportedCommentsRoute: typeof AdminReportedCommentsRoute
  AdminReportedPostsRoute: typeof AdminReportedPostsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBadgesRoute: AdminBadgesRoute,
  AdminBannedDomainsRoute: AdminBannedDomainsRoute,
  AdminBulkModerationRoute: AdminBulkModerationRoute,
  AdminFilteredRoute: AdminFilteredRoute,
  AdminModLogRoute: AdminModLogRoute,
  AdminReportedCommentsRoute: AdminReportedCommentsRoute,
  AdminReportedPostsRoute: AdminReportedPostsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtusernameRoute: AtusernameRoute,
  AtmeRoute: AtmeRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminsRoute: AdminsRoute,
  BannedRoute: BannedRoute,
  CatalogRoute: CatalogRoute,
  CommentsRoute: CommentsRoute,
  ForgotRoute: ForgotRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormattingRoute: FormattingRoute,
  LogRoute: LogRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MeRoute: MeRoute,
  ModLogRoute: ModLogRoute,
  ModlogRoute: ModlogRoute,
  NotificationsRoute: NotificationsRoute,
  Random_postRoute: Random_postRoute,
  Random_userRoute: Random_userRoute,
  ResetRoute: ResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  SubmitRoute: SubmitRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AtusernamePostsRoute: AtusernamePostsRoute,
  CommentIdRoute: CommentIdRoute,
  PostIdRoute: PostIdRoute,
  UUsernameRoute: UUsernameRoute,
  UMeRoute: UMeRoute,
  AtusernameSavedCommentsRoute: AtusernameSavedCommentsRoute,
  AtusernameSavedPostsRoute: AtusernameSavedPostsRoute,
  UUsernameFollowersRoute: UUsernameFollowersRoute,
  UUsernameFollowingRoute: UUsernameFollowingRoute,
  UUsernamePostsRoute: UUsernamePostsRoute,
  UUsernameSavedCommentsRoute: UUsernameSavedCommentsRoute,
  UUsernameSavedPostsRoute: UUsernameSavedPostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
